# Configuration file used by genja to generate this website.
# See https://github.com/wigging/genja for more info about genja.

base_url = "https://gavinw.me"
markdown_dir = "notes"
template_dir = "templates"
output_dir = "."