# This configuration file is used by Genja to generate the website
# See https://github.com/wigging/genja for more info about Genja

base_url = "https://gavinw.me"
posts_output = "notes"
site_output = "."
title = "Gavin Wiggins"
