- name: WeathrClip
  desc: WeathrClip provided current weather conditions, 5-day forecast, hourly forecast, and precipitation radar for the Mac and iPhone. I discontinued this app because the Weather Underground API is no longer available.

- name: Un1ts
  desc: Un1ts was a comprehensive unit converter for the Mac written in Objective-C. I’m currently working on a new version of the app written in Swift.
